keyword_variants = {
    "Python": ["python", "py"],
    "Java": ["java"],
    "JavaScript": ["javascript", "js"],
    "C#": ["c#", "csharp"],
    "C++": ["c++", "cpp"],
    "PHP": ["php"],
    "TypeScript": ["typescript", "ts"],
    "Swift": ["swift"],
    "Rust": ["rust"],
    "Objective-C": ["objective-c", "objc"],
    "Go": ["go", "golang"],
    "Kotlin": ["kotlin"],
    "Matlab": ["matlab"],
    "Dart": ["dart"],
    "Ruby": ["ruby"],
    "VBA": ["vba", "visual basic for applications"],
    "Powershell": ["powershell"],
    "Ada": ["ada"],
    "Scala": ["scala"],
    "Lua": ["lua"],
    "Abap": ["abap"],
    "Visual Basic": ["visual basic", "vb"],
    "Julia": ["julia"],
    "Perl": ["perl"],
    "Haskell": ["haskell"],
    "Groovy": ["groovy"],
    "Cobol": ["cobol"],
    "Delphi/Pascal": ["delphi", "pascal"],
    "Oracle": ["oracle"],
    "MySQL": ["mysql"],
    "SQL Server": ["sql server", "mssql", "microsoft sql server"],
    "PostgreSQL": ["postgresql", "postgres"],
    "MongoDB": ["mongodb"],
    "Microsoft Access": ["microsoft access", "access"],
    "Firebase": ["firebase"],
    "Redis": ["redis"],
    "Splunk": ["splunk"],
    "SQLite": ["sqlite"],
    "Elasticsearch": ["elasticsearch", "elastic search"],
    "MariaDB": ["mariadb"],
    "SAP HANA": ["sap hana", "hana"],
    "DynamoDB": ["dynamodb", "amazon dynamodb"],
    "DB2": ["db2", "ibm db2"],
    "Apache Hive": ["apache hive", "hive"],
    "Neo4j": ["neo4j"],
    "FileMaker": ["filemaker"],
    "Solr": ["solr", "apache solr"],
    "Firebird": ["firebird"],
    "Ingres": ["ingres"],
    "Sybase": ["sybase"],
    "Hbase": ["hbase"],
    "CouchBase": ["couchbase"],
    "Memcached": ["memcached"],
    "Riak": ["riak"],
    "Informix": ["informix", "ibm informix"],
    "CouchDB": ["couchdb"],
    "dBase": ["dbase"],
    "Netezza": ["netezza", "ibm netezza"],
    "Full-stack Developer": ["full-stack", "full stack", "fullstack"],
    "Back-end Developer": ["back-end", "backend", "back end"],
    "Front-end Developer": ["front-end", "frontend", "front end"],
    "Desktop or Enterprise Applications Developer": ["desktop developer", "enterprise applications developer", "desktop applications developer"],
    "Mobile Developer": ["mobile developer", "mobile app developer", "mobile applications developer"],
    "Engineering Manager": ["engineering manager", "manager engineering"],
    "Embedded Applications or Devices Developer": ["embedded developer", "embedded systems developer", "embedded applications developer"],
    "Data Scientist or Machine Learning Specialist": ["data scientist", "machine learning specialist", "ml specialist"],
    "DevOps Specialist": ["devops", "devops engineer", "devops specialist"],
    "Research & Development Role": ["r&d", "research and development"],
    "Senior Executive": ["c-suite", "vp", "senior executive"],
    "Data Engineer": ["data engineer", "ingeniero de datos"],
    "Cloud Infrastructure Engineer": ["cloud infrastructure engineer", "cloud engineer"],
    "Game or Graphics Developer": ["game developer", "graphics developer", "game and graphics developer"],
    "Data or Business Analyst": ["data analyst", "business analyst"],
    "System Administrator": ["system administrator", "sysadmin"],
    "Project Manager": ["project manager"],
    "QA or Test Developer": ["qa developer", "test developer", "quality assurance developer"],
    "Security Professional": ["security professional", "security engineer"],
    "Product Manager": ["product manager"],
    "Site Reliability Engineer": ["site reliability engineer", "sre"],
    "Developer Experience": ["developer experience", "devex"],
    "Blockchain Developer": ["blockchain developer", "blockchain engineer"],
    "Hardware Engineer": ["hardware engineer"],
    "Designer": ["designer", "graphic designer"],
    "Database Administrator": ["database administrator", "dba"],
    "Developer Advocate": ["developer advocate", "devrel"],
}
